# Generated by Django 4.2.2 on 2023-06-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Show Date')),
                ('review', models.TextField(max_length=250)),
            ],
        ),
    ]
