# Generated by Django 4.2.2 on 2023-06-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_theater_remove_show_review_show_user_review_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='seen',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='wishlist',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
