# Generated by Django 4.2.2 on 2023-06-20 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_show_seen_show_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='user',
        ),
        migrations.RemoveField(
            model_name='show',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='show',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='show',
            name='seen',
            field=models.ManyToManyField(related_name='seen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
