# Generated by Django 4.2.2 on 2023-06-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_theater_maps_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='theater',
            options={'ordering': ['name']},
        ),
    ]
